ConfOptions:
  Threshold: 16
  WriteRoutesToFile: false
  RangeAddress: 65536
  Originators: 1000
  Iterations: 250_000
  EdgeLock: true
  MaxProximityOrder: 16
  NetworkSize: 10_000
  BinSize: 16
  IterationMeansUniqueChunk: false
  SameOriginator: false
  RandomSeed: 123456789
  OutputOptions:
    AverageFractionOfTotalRewardsK8: false
    RewardFairnessForForwardingAction: false
    RewardFairnessForAllActions: false
    AverageNumberOfHops: true
    RewardFairnessForStoringAction: false
    MeanRewardPerForward: true
    AverageFractionOfTotalRewardsK16: true
    NegativeIncome: false
  OutputEnabled: false
  DebugInterval: 1_000_000
  WriteStatesToFile: false
  Price: 1
  Bits: 16
  RequestsPerSecond: 12500
  RefreshRate: 8
  DebugPrints: false
  PrecomputeRespNodes: true
  NumGoroutines: 13
Experiment:
  Name: custom
CustomExperiment:
  MaxPOCheckEnabled: true
  ThresholdEnabled: false
  AdjustableThreshold: false
  CacheIsEnabled: false
  OnlyOriginatorPays: false
  PayIfOrigPays: false
  PreferredChunks: false
  ForgivenessEnabled: false
  RetryWithAnotherPeer: false
  WaitingEnabled: false
  PaymentEnabled: false
  PayOnlyForCurrentRequest: false
  ForwardersPayForceOriginatorToPay: false

