ConfOptions:
  Threshold: 16
  WriteRoutesToFile: true
  RangeAddress: 65536
  Originators: 1000
  Iterations: 100_000_000
  EdgeLock: true
  MaxProximityOrder: 16
  NetworkSize: 10000
  RandomSeed: 123456789
  BinSize: 16
  IterationMeansUniqueChunk: false
  SameOriginator: false
  OutputOptions:
    AverageFractionOfTotalRewardsK8: false
    RewardFairnessForForwardingAction: false
    RewardFairnessForAllActions: false
    AverageNumberOfHops: false
    AverageFractionOfTotalRewardsK16: false
    MeanRewardPerForward: false
    RewardFairnessForStoringAction: false
    NegativeIncome: false
  OutputEnabled: true
  DebugInterval: 1_000_000
  WriteStatesToFile: false
  Price: 1
  Bits: 16
  RequestsPerSecond: 12500
  RefreshRate: 8
  DebugPrints: false
  PrecomputeRespNodes: true
  NumGoroutines: 13
Experiment:
  Name: custom
CustomExperiment:
  MaxPOCheckEnabled: true
  ThresholdEnabled: true
  AdjustableThreshold: false
  CacheIsEnabled: false
  OnlyOriginatorPays: false
  PayIfOrigPays: false
  PreferredChunks: false
  ForgivenessEnabled: true
  RetryWithAnotherPeer: false
  WaitingEnabled: false
  PaymentEnabled: false
  PayOnlyForCurrentRequest: false
  ForwardersPayForceOriginatorToPay: false

